# Generated by Django 2.2.7 on 2019-12-01 12:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rfid', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('event_name', models.CharField(blank=True, default='', max_length=30)),
                ('registration_number', models.CharField(blank=True, default='', max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None)),
                ('email', models.EmailField(blank=True, editable=False, max_length=253)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
