# Generated by Django 2.2.7 on 2019-12-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
