# Generated by Django 2.2.7 on 2019-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_auto_20191201_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(blank=True, max_length=253),
        ),
    ]
